# Initial schema for HBL music rewards.
import decimal
import uuid
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PlatformConfig',
            fields=[
                ('id', models.PositiveSmallIntegerField(default=1, editable=False, primary_key=True, serialize=False)),
                ('withdrawal_min', models.DecimalField(decimal_places=2, default=decimal.Decimal('200.00'), max_digits=12)),
                ('withdrawal_fee_percent', models.DecimalField(decimal_places=2, default=decimal.Decimal('0.00'), max_digits=5)),
                ('referral_first_deposit_percent', models.DecimalField(decimal_places=2, default=decimal.Decimal('0.00'), max_digits=5)),
                ('daily_listen_reward_cap', models.DecimalField(decimal_places=2, default=decimal.Decimal('0.00'), help_text='0 = sin tope diario global por usuario.', max_digits=12)),
                ('referral_activity_days', models.PositiveSmallIntegerField(default=7)),
                ('signup_bonus', models.DecimalField(decimal_places=2, default=decimal.Decimal('0.00'), max_digits=12)),
                ('maintenance_mode', models.BooleanField(default=False)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={'verbose_name': 'Configuración HBL', 'verbose_name_plural': 'Configuración HBL'},
        ),
        migrations.CreateModel(
            name='PaymentMethod',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kind', models.CharField(choices=[('bank', 'Transferencia bancaria'), ('binance_pay', 'Binance Pay'), ('binance_id', 'Binance Pay ID / Binance ID'), ('usdt_trc20', 'USDT TRC20'), ('usdt_bep20', 'USDT BEP20'), ('crypto_other', 'Otra criptomoneda/red'), ('remittance', 'Giro / remesa'), ('mobile_wallet', 'Billetera móvil')], max_length=24)),
                ('label', models.CharField(max_length=100)),
                ('currency', models.CharField(default='NIO', max_length=12)),
                ('network', models.CharField(blank=True, max_length=40)),
                ('destination', models.CharField(blank=True, max_length=255)),
                ('instructions', models.TextField(blank=True)),
                ('min_amount', models.DecimalField(decimal_places=8, default=decimal.Decimal('1.00000000'), max_digits=18)),
                ('balance_rate', models.DecimalField(decimal_places=8, default=decimal.Decimal('1.00000000'), help_text='Cuántas unidades de saldo HBL (C$) se acreditan por 1 unidad de la moneda de pago.', max_digits=18)),
                ('active', models.BooleanField(default=True)),
                ('sort_order', models.PositiveSmallIntegerField(default=10)),
            ],
            options={'ordering': ['sort_order', 'label']},
        ),
        migrations.CreateModel(
            name='ReferralTier',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=80)),
                ('min_active_referrals', models.PositiveIntegerField(unique=True)),
                ('weekly_salary', models.DecimalField(decimal_places=2, default=decimal.Decimal('0.00'), max_digits=12)),
                ('active', models.BooleanField(default=True)),
            ],
            options={'ordering': ['min_active_referrals']},
        ),
        migrations.CreateModel(
            name='Track',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=160)),
                ('artist', models.CharField(blank=True, max_length=160)),
                ('slug', models.SlugField(max_length=180, unique=True)),
                ('cover', models.ImageField(blank=True, null=True, upload_to='hbl/covers/')),
                ('cover_url', models.URLField(blank=True)),
                ('audio', models.FileField(blank=True, null=True, upload_to='hbl/audio/')),
                ('audio_url', models.URLField(blank=True)),
                ('duration_seconds', models.PositiveIntegerField(default=180)),
                ('min_listen_seconds', models.PositiveIntegerField(default=30)),
                ('reward_amount', models.DecimalField(decimal_places=2, default=decimal.Decimal('1.00'), max_digits=12)),
                ('daily_user_limit', models.PositiveSmallIntegerField(default=1)),
                ('active', models.BooleanField(default=True)),
                ('featured', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={'ordering': ['-featured', 'title']},
        ),
        migrations.CreateModel(
            name='PayoutAccount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kind', models.CharField(choices=[('bank', 'Cuenta bancaria'), ('binance_id', 'Binance Pay ID / Binance ID'), ('usdt_trc20', 'USDT TRC20'), ('usdt_bep20', 'USDT BEP20'), ('crypto_other', 'Otra wallet'), ('remittance', 'Giro / remesa'), ('mobile_wallet', 'Billetera móvil')], max_length=24)),
                ('label', models.CharField(max_length=100)),
                ('holder_name', models.CharField(blank=True, max_length=140)),
                ('identifier', models.CharField(max_length=255)),
                ('network', models.CharField(blank=True, max_length=40)),
                ('is_default', models.BooleanField(default=False)),
                ('active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='hbl_payout_accounts', to=settings.AUTH_USER_MODEL)),
            ],
            options={'ordering': ['-is_default', 'label']},
        ),
        migrations.CreateModel(
            name='RewardLedger',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('kind', models.CharField(choices=[('listen', 'Escucha'), ('referral', 'Referido'), ('referral_salary', 'Sueldo por referidos'), ('deposit', 'Recarga'), ('withdrawal', 'Retiro'), ('withdrawal_refund', 'Reembolso de retiro'), ('signup', 'Registro'), ('admin', 'Ajuste administrativo')], max_length=32)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=14)),
                ('balance_after', models.DecimalField(decimal_places=2, max_digits=14)),
                ('reference', models.CharField(blank=True, db_index=True, max_length=100)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='hbl_ledger', to=settings.AUTH_USER_MODEL)),
            ],
            options={'ordering': ['-created_at']},
        ),
        migrations.CreateModel(
            name='ListeningSession',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('status', models.CharField(choices=[('started', 'Iniciada'), ('rewarded', 'Recompensada'), ('expired', 'Expirada'), ('rejected', 'Rechazada')], default='started', max_length=16)),
                ('started_at', models.DateTimeField(auto_now_add=True)),
                ('rewarded_at', models.DateTimeField(blank=True, null=True)),
                ('reward_amount', models.DecimalField(decimal_places=2, default=decimal.Decimal('0.00'), max_digits=12)),
                ('verified_seconds', models.PositiveIntegerField(default=0)),
                ('last_ping_at', models.DateTimeField(blank=True, null=True)),
                ('client_nonce', models.CharField(blank=True, db_index=True, max_length=64)),
                ('ip_hash', models.CharField(blank=True, max_length=64)),
                ('track', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='listening_sessions', to='hbl_core.track')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='hbl_listening_sessions', to=settings.AUTH_USER_MODEL)),
            ],
            options={'ordering': ['-started_at']},
        ),
        migrations.CreateModel(
            name='Deposit',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('amount', models.DecimalField(decimal_places=2, help_text='Saldo HBL a acreditar, normalmente NIO.', max_digits=14)),
                ('currency', models.CharField(default='NIO', max_length=12)),
                ('payment_amount', models.DecimalField(decimal_places=8, default=decimal.Decimal('0.00000000'), max_digits=18)),
                ('payment_currency', models.CharField(default='NIO', max_length=12)),
                ('balance_rate', models.DecimalField(decimal_places=8, default=decimal.Decimal('1.00000000'), max_digits=18)),
                ('status', models.CharField(choices=[('pending', 'Pendiente'), ('processing', 'Procesando'), ('approved', 'Aprobada'), ('rejected', 'Rechazada'), ('expired', 'Expirada')], default='pending', max_length=16)),
                ('txid', models.CharField(blank=True, db_index=True, max_length=180)),
                ('reference', models.CharField(blank=True, max_length=180)),
                ('proof', models.ImageField(blank=True, null=True, upload_to='hbl/deposit_proofs/%Y/%m/')),
                ('merchant_trade_no', models.CharField(blank=True, max_length=32, null=True, unique=True)),
                ('prepay_id', models.CharField(blank=True, max_length=64)),
                ('checkout_url', models.URLField(blank=True, max_length=600)),
                ('transaction_id', models.CharField(blank=True, max_length=80)),
                ('notes', models.TextField(blank=True)),
                ('submitted_at', models.DateTimeField(auto_now_add=True)),
                ('processed_at', models.DateTimeField(blank=True, null=True)),
                ('payment_method', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='deposits', to='hbl_core.paymentmethod')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='hbl_deposits', to=settings.AUTH_USER_MODEL)),
            ],
            options={'ordering': ['-submitted_at']},
        ),
        migrations.CreateModel(
            name='Withdrawal',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('payout_kind', models.CharField(blank=True, max_length=24)),
                ('payout_label', models.CharField(blank=True, max_length=100)),
                ('payout_identifier', models.CharField(blank=True, max_length=255)),
                ('payout_network', models.CharField(blank=True, max_length=40)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=14)),
                ('fee', models.DecimalField(decimal_places=2, default=decimal.Decimal('0.00'), max_digits=14)),
                ('net_amount', models.DecimalField(decimal_places=2, max_digits=14)),
                ('status', models.CharField(choices=[('pending', 'Pendiente'), ('processing', 'Procesando'), ('paid', 'Pagado'), ('rejected', 'Rechazado'), ('canceled', 'Cancelado')], default='pending', max_length=16)),
                ('admin_reference', models.CharField(blank=True, max_length=180)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('processed_at', models.DateTimeField(blank=True, null=True)),
                ('payout_account', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='withdrawals', to='hbl_core.payoutaccount')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='hbl_withdrawals', to=settings.AUTH_USER_MODEL)),
            ],
            options={'ordering': ['-created_at']},
        ),
        migrations.CreateModel(
            name='ReferralEarning',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kind', models.CharField(choices=[('first_deposit', 'Primera recarga'), ('manual', 'Manual')], max_length=24)),
                ('base_amount', models.DecimalField(decimal_places=2, default=decimal.Decimal('0.00'), max_digits=14)),
                ('percent', models.DecimalField(decimal_places=2, default=decimal.Decimal('0.00'), max_digits=5)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=14)),
                ('reference', models.CharField(max_length=100, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('referred', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='hbl_generated_referral_earnings', to=settings.AUTH_USER_MODEL)),
                ('sponsor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='hbl_referral_earnings', to=settings.AUTH_USER_MODEL)),
            ],
            options={'ordering': ['-created_at']},
        ),
        migrations.CreateModel(
            name='ReferralPayroll',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('week_start', models.DateField()),
                ('active_referrals', models.PositiveIntegerField(default=0)),
                ('amount', models.DecimalField(decimal_places=2, default=decimal.Decimal('0.00'), max_digits=12)),
                ('status', models.CharField(choices=[('pending', 'Pendiente'), ('paid', 'Pagado'), ('canceled', 'Cancelado')], default='pending', max_length=16)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('paid_at', models.DateTimeField(blank=True, null=True)),
                ('tier', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='hbl_core.referraltier')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='hbl_referral_payrolls', to=settings.AUTH_USER_MODEL)),
            ],
            options={'ordering': ['-week_start', '-amount']},
        ),
        migrations.AddIndex(model_name='track', index=models.Index(fields=['active', 'featured'], name='hbl_core_tr_active_02d0ae_idx')),
        migrations.AddIndex(model_name='rewardledger', index=models.Index(fields=['user', 'kind', 'created_at'], name='hbl_core_re_user_id_73dc8b_idx')),
        migrations.AddIndex(model_name='listeningsession', index=models.Index(fields=['user', 'status', 'started_at'], name='hbl_core_li_user_id_20e3a1_idx')),
        migrations.AddIndex(model_name='listeningsession', index=models.Index(fields=['user', 'track', 'status'], name='hbl_core_li_user_id_71a1a7_idx')),
        migrations.AddIndex(model_name='deposit', index=models.Index(fields=['status', 'submitted_at'], name='hbl_core_de_status_558235_idx')),
        migrations.AddConstraint(model_name='deposit', constraint=models.UniqueConstraint(condition=~models.Q(txid=''), fields=('txid',), name='uniq_hbl_nonempty_txid')),
        migrations.AddIndex(model_name='withdrawal', index=models.Index(fields=['status', 'created_at'], name='hbl_core_wi_status_a4ab3c_idx')),
        migrations.AddConstraint(model_name='referralpayroll', constraint=models.UniqueConstraint(fields=('user', 'week_start'), name='uniq_hbl_referral_payroll_week')),
    ]
