# Generated by Django 5.2.17 on 2026-08-18 23:24

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hbl_core', '0007_labels_and_base_help'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='deposit',
            new_name='hbl_core_de_status_be9473_idx',
            old_name='hbl_core_de_status_558235_idx',
        ),
        migrations.RenameIndex(
            model_name='listeningsession',
            new_name='hbl_core_li_user_id_8e9724_idx',
            old_name='hbl_core_li_user_id_20e3a1_idx',
        ),
        migrations.RenameIndex(
            model_name='listeningsession',
            new_name='hbl_core_li_user_id_53d157_idx',
            old_name='hbl_core_li_user_id_71a1a7_idx',
        ),
        migrations.RenameIndex(
            model_name='rewardledger',
            new_name='hbl_core_re_user_id_aa0b40_idx',
            old_name='hbl_core_re_user_id_73dc8b_idx',
        ),
        migrations.RenameIndex(
            model_name='track',
            new_name='hbl_core_tr_active_0e7f5c_idx',
            old_name='hbl_core_tr_active_02d0ae_idx',
        ),
        migrations.RenameIndex(
            model_name='withdrawal',
            new_name='hbl_core_wi_status_cac77a_idx',
            old_name='hbl_core_wi_status_a4ab3c_idx',
        ),
        migrations.AlterField(
            model_name='deposit',
            name='amount',
            field=models.DecimalField(decimal_places=2, help_text='Saldo HBL a acreditar expresado en la moneda base vigente.', max_digits=14),
        ),
        migrations.AlterField(
            model_name='platformconfig',
            name='exchange_rate_usd_nio',
            field=models.DecimalField(decimal_places=4, default=Decimal('36.6200'), help_text='Unidades de la moneda base equivalentes a US$1. Se conserva por compatibilidad; las tasas activas se administran en Monedas.', max_digits=10),
        ),
        migrations.AlterField(
            model_name='platformconfig',
            name='minimum_deposit_usd',
            field=models.DecimalField(decimal_places=2, default=Decimal('100.00'), help_text='Recarga mínima global expresada en USD. Se convierte a la moneda base usando la tasa USD activa.', max_digits=12),
        ),
    ]
