# Generated by Django 5.2.17 on 2026-08-26 13:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hbl_core', '0010_nowpayments_deposits'),
    ]

    operations = [
        migrations.AddField(
            model_name='deposit',
            name='provider_actual_paid',
            field=models.DecimalField(blank=True, decimal_places=8, max_digits=18, null=True),
        ),
    ]
