# Generated by Django 5.2.17 on 2026-08-26 13:47

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hbl_core', '0011_deposit_provider_actual_paid'),
    ]

    operations = [
        migrations.AddField(
            model_name='deposit',
            name='provider_fee_amount',
            field=models.DecimalField(decimal_places=8, default=Decimal('0E-8'), max_digits=18),
        ),
    ]
