# Generated by Django 5.2.17 on 2026-08-26 14:28

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hbl_core', '0012_deposit_provider_fee_amount'),
    ]

    operations = [
        migrations.AddField(
            model_name='deposit',
            name='sender_network_fee_estimate',
            field=models.DecimalField(decimal_places=8, default=Decimal('0E-8'), max_digits=18),
        ),
        migrations.AddField(
            model_name='paymentmethod',
            name='sender_network_fee_estimate',
            field=models.DecimalField(decimal_places=8, default=Decimal('1.00000000'), help_text='Reserva estimada que la billetera del usuario puede cobrar por enviar. No se transfiere a HBL.', max_digits=18),
        ),
    ]
